import type { Metadata } from "next";
import { Jersey_25 } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/navbar/page";
import GoogleMaps from "./_components/googlemaps/page";

const jersey25 = Jersey_25({
  weight: '400', // Only 400 is available for this font
  subsets: ['latin'],
  variable: '--font-jersey',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jersey25.variable} antialiased`}>
        <NavBar />
        <div className="flex justify-between bg-gray-200">
          <section className="w-3/8 h-1000 border-r-2 border-black">
            {children}
          </section>
          <GoogleMaps />
        </div>
      </body>
    </html>
  );
}
